#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] = File.expand_path("../Gemfile", __FILE__)
require 'bundler/setup'

require 'optparse'
require 'rfusefs'

class PacketFS < FuseFS::FuseDir

  def contents(path)
    ['hello.txt']
  end

  def file?(path)
    path == '/hello.txt'
  end

  def read_file(path)
    "Hello, World!\n"
  end

end

root = PacketFS.new
FuseFS.set_root(root)

mount_dir = ARGV.shift
FuseFS.mount_under(mount_dir, *ARGV)

params = ARGV.getopts('d')
unless params['d']
    Process.daemon
end
FuseFS.run
