#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] = File.expand_path("../Gemfile", __FILE__)
require 'bundler/setup'

require 'optparse'
require 'rfusefs'

class PacketFS < FuseFS::FuseDir

  def initialize(storage)
    @storage = storage
  end

  def contents(path)
    puts @storage + path
    Dir::entries(@storage + path)
  end

  def file?(path)
    File.file?(@storage + path)
  end

  def directory?(path)
    File.directory?(@storage + path)
  end

  def read_file(path)
    File.read(@storage + path)
  end

end

mount_dir = ARGV.shift
storage = ARGV.shift

root = PacketFS.new(storage)
FuseFS.set_root(root)
FuseFS.mount_under(mount_dir, *ARGV)

params = ARGV.getopts('d')
unless params['d']
    Process.daemon
end
FuseFS.run
