#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] = File.expand_path("../Gemfile", __FILE__)
require 'bundler/setup'

require 'optparse'
require 'sinatra'

dir = ARGV.shift
Dir.chdir(dir)

arg_params = ARGV.getopts('p')
port = arg_params['p'] || 55000

set :port, port

put '/*' do |path|
  if params.include?('dir')
    Dir.mkdir(path)
  else
    File.write(path, request.body.read)
  end

  200
end

delete '/*' do |path|
  if params.include?('dir')
    Dir.rmdir(path)
  else
    File.delete(path)
  end

  200
end
