#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] = File.expand_path("../Gemfile", __FILE__)
require 'bundler/setup'

require 'rfusefs'

class PacketFS < FuseFS::FuseDir

  def contents(path)
    ['hello.txt']
  end

  def file?(path)
    path == '/hello.txt'
  end

  def read_file(path)
    "Hello, World!\n"
  end

end

# Usage: #{$0} mountpoint [mount_options]
# FuseFS.main() { |options| HelloDir.new }

root = PacketFS.new
FuseFS.set_root(root)
FuseFS.mount_under("/tmp/packet", *ARGV)
FuseFS.run
